### ISSUE TITLE
Projection does not work in addRelation()

### ISSUE THREAD

**Issue by vavarun** [nodkz/graphql-compose-elasticsearch#23]
```
AgentEsTC.addRelation(
  'user',
  {
    resolver: () => UserTC.getResolver('findById'),
    prepareArgs: {
      _id: source => source.user_id
    },
    projection: { user_id: true },
  }
);
```

I have to provide user_id in my resolver to be able to use findById in addRelation. If you could help me query this?

**Comment by nodkz** [comment]
The error was fixed in the main package [graphql-compose@2.9.4](https://github.com/nodkz/graphql-compose/releases). Please install the new version and confirm that it works like in the code above.

Demo: https://github.com/nodkz/graphql-compose-elasticsearch/commit/f4e6029ed8c288fa2dd763d81b6ee14aac0825b2
